services:
  api:
    ports:
      - "127.0.0.1:8000:8000"
    environment:
      APP_PUBLIC_URL: http://localhost:8000
    volumes:
      - ${COG_DATA_DIR:-./dades_cog}:/app/dades_cog
      - ./main.py:/app/main.py
      - ${MBTILES_DATA_DIR:-./mbtiles}:/app/mbtiles

  worker:
    environment:
      APP_PUBLIC_URL: http://localhost:8000
    volumes:
      - ${MBTILES_DATA_DIR:-./mbtiles}:/app/mbtiles

  cleanup:
    volumes:
      - ${MBTILES_DATA_DIR:-./mbtiles}:/app/mbtiles

networks:
  webproxy:
    external: false
    driver: bridge
